/** @jsxImportSource @emotion/react */
import React from 'react';
import {Container} from 'react-bootstrap';
import TitleH1 from '../Components/TitleH1.jsx';
import { css} from '@emotion/react';

function LegalNotice (){
    return <Container>
        <TitleH1>Mentions Légales</TitleH1>
        <div
            css={css`
                margin-bottom: 50px;
            `}
        >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque volutpat ultrices feugiat. Sed blandit gravida tellus sed efficitur. In ac imperdiet urna. Mauris tincidunt pretium justo id mollis. Nam quis est elementum, maximus mi in, gravida ante. In elementum sem et velit commodo, eget blandit dolor iaculis. Duis in leo vitae odio fermentum gravida. Etiam non arcu pretium, accumsan sem vel, facilisis felis. Fusce vitae augue consequat, pellentesque nulla tempus, blandit sem. Aenean dictum sapien lacus, non porta augue imperdiet eu. Duis pulvinar faucibus mi sit amet egestas. Integer feugiat ipsum vitae lacus sollicitudin, vel pharetra turpis auctor. Nullam ornare lorem ut ipsum posuere, tempor pulvinar velit egestas. Vivamus tristique urna felis, ut convallis metus varius vitae. Aliquam imperdiet erat et purus rutrum, sed mattis neque finibus.

            Ut posuere, enim quis sodales porta, massa eros ultricies erat, vitae interdum lacus quam a urna. Donec scelerisque nulla nec lacus consectetur, lacinia vestibulum orci vulputate. Phasellus a eros et lectus pretium iaculis. Vestibulum et mollis massa. In dignissim mi nisi, placerat tincidunt augue finibus quis. Mauris pretium nulla nec quam ornare sollicitudin. Suspendisse magna massa, finibus euismod blandit eu, hendrerit id dui. Cras fermentum justo sapien, id tempor massa imperdiet vitae. In quis laoreet mi, sed laoreet risus.

            Nullam sit amet pretium libero. Phasellus quis pretium ex, sodales vestibulum nisl. Mauris pulvinar felis in ligula rutrum, at ultrices enim pulvinar. Pellentesque consequat, odio ac scelerisque tristique, sem risus pulvinar tortor, et consectetur sem risus nec turpis. In iaculis ante molestie est efficitur, ac sollicitudin urna consequat. In hac habitasse platea dictumst. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

            In hac habitasse platea dictumst. Ut sed commodo augue, consectetur aliquam erat. Phasellus consectetur blandit dui eu fermentum. Donec in lacinia tortor. Aenean faucibus nisl id justo tempor, aliquam lacinia arcu convallis. Mauris arcu felis, venenatis sed commodo sed, varius sodales ligula. Curabitur condimentum libero nec nunc sagittis, sit amet luctus mi consectetur. Curabitur porttitor dui eget enim tincidunt tincidunt. Aliquam molestie ex et aliquam porttitor. Aenean ante quam, porttitor sed tempus in, commodo eu arcu. Nulla lacinia fringilla sem vitae efficitur. Vestibulum sit amet metus commodo, pretium ante vel, egestas neque. Duis venenatis tincidunt odio, in elementum urna lacinia eget. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

            Nullam id ipsum luctus ligula varius sollicitudin a a augue. Nullam lectus eros, finibus vitae tortor eget, imperdiet pretium odio. Fusce mauris arcu, porta a congue sed, molestie a elit. Morbi pulvinar felis ac nisi mollis, eu hendrerit turpis volutpat. Ut hendrerit dui in iaculis scelerisque. Proin gravida orci id justo blandit, vitae euismod mi finibus. Quisque auctor libero eu suscipit rhoncus.

            Vestibulum ullamcorper cursus quam in finibus. Integer vulputate facilisis magna, vel cursus lacus ultrices et. Curabitur euismod id turpis accumsan tristique. Ut interdum nunc ut leo sagittis, vel ullamcorper libero lobortis. Maecenas at posuere eros. Sed in velit et nulla blandit accumsan. In hac habitasse platea dictumst.

            Duis consequat nunc leo, eu dictum sem lobortis vel. Vestibulum vehicula augue tristique, ultricies ante ac, aliquet nulla. Phasellus in bibendum massa. Etiam tincidunt, arcu vitae rutrum dapibus, justo felis mollis massa, vitae faucibus lacus nisl id ipsum. Mauris euismod massa massa, sit amet tristique ex porttitor sit amet. Nulla rhoncus vulputate leo. Donec a risus volutpat, volutpat enim nec, placerat ligula. Nullam nec lobortis ipsum, quis laoreet ligula.

            Sed aliquam elit vitae augue pulvinar, sit amet posuere lacus viverra. Morbi pharetra augue dui, et rhoncus odio euismod vel. Etiam ultrices mi non accumsan bibendum. Duis quis mattis mi. Pellentesque varius convallis condimentum. Praesent mollis dignissim ligula ut laoreet. Pellentesque id felis metus.

            Maecenas interdum urna eu mi dapibus finibus. Aliquam molestie elementum tristique. Vivamus consectetur odio erat, blandit bibendum lorem congue tincidunt. Vivamus pulvinar nisi quam, ut molestie quam ullamcorper sit amet. Donec nec ante eu quam pellentesque rhoncus quis eget ante. Pellentesque aliquam enim metus, ac condimentum dui scelerisque eu. Cras blandit tortor tortor, eget cursus orci rutrum vel. Nunc finibus quam sit amet consequat gravida. Curabitur suscipit porttitor nisl. Sed sed massa ut felis fringilla dictum eget at nibh. Maecenas tristique augue ipsum, eget tempor libero egestas facilisis. Donec et felis porta, ultricies nibh in, rutrum purus. Maecenas aliquet eget arcu vel feugiat.

            Sed porttitor, leo vel blandit egestas, ipsum ligula molestie ipsum, tempus sagittis nisi neque vel nibh. Aliquam vitae odio sed ex congue pulvinar. Integer feugiat quam vel posuere imperdiet. Nam sit amet quam purus. Nam vitae eleifend metus, eu semper tortor. Cras ante leo, scelerisque a porttitor et, tristique quis elit. Proin ornare rhoncus elit varius molestie. Phasellus fermentum, arcu aliquet tempor tempor, libero velit mollis nunc, sit amet vestibulum velit quam quis dui. Integer porttitor tellus vestibulum sapien rutrum feugiat. Aliquam hendrerit sapien at eros malesuada dapibus. Nunc imperdiet vulputate porta. Mauris id dignissim lorem, vitae convallis massa. Nunc aliquam auctor neque vitae maximus. Curabitur maximus dictum turpis vitae tincidunt. Ut vitae placerat lorem, sed commodo mauris.

            Quisque euismod nisi ac facilisis ultricies. Aliquam lacus lacus, volutpat vel quam et, ornare sollicitudin augue. In mattis fermentum tortor, lobortis malesuada augue elementum in. Pellentesque sodales mollis nunc, id hendrerit felis suscipit nec. Sed dictum vulputate sapien, nec sodales lectus pharetra et. Aliquam quis ante semper, consequat justo a, dapibus felis. Nam commodo bibendum finibus. Mauris lobortis lorem id molestie aliquam. Donec id ornare sem. Vivamus consectetur hendrerit sem maximus consequat. Aliquam ullamcorper, enim a rhoncus volutpat, quam augue vulputate dolor, ut finibus nulla purus a erat.

            Etiam nisl sem, vehicula ac facilisis ac, tempus vitae lorem. Donec in interdum nisi. Etiam convallis, dui ac eleifend maximus, felis lacus rutrum tellus, at euismod nisl diam sed ligula. Pellentesque non iaculis nulla. Aenean sit amet bibendum leo. Ut commodo suscipit accumsan. Sed dolor urna, venenatis ac gravida vitae, dapibus quis arcu. Nulla laoreet velit at orci pulvinar pretium. Donec id felis efficitur, rutrum purus vitae, elementum ipsum. Sed vel porta orci. Nullam a nisl quis lorem viverra maximus. In fringilla, ex sit amet iaculis blandit, massa quam elementum diam, ultrices sodales eros nisi id sapien. Proin lobortis arcu at justo imperdiet tincidunt. Proin nec rutrum enim, a scelerisque eros. Quisque diam nulla, cursus dignissim consequat vitae, tempus non velit. Duis sed metus accumsan, imperdiet massa at, ultrices quam.

            Nulla cursus eros nibh, nec mattis nisl pretium eget. Cras sed porttitor mauris. Curabitur consequat arcu eu metus porta suscipit. Praesent pharetra, dui nec malesuada tempus, metus dolor rutrum tellus, eget imperdiet nunc dolor in libero. Phasellus nec tempus lacus. Vivamus pharetra luctus elit. Maecenas orci enim, consectetur non posuere malesuada, maximus in neque. Nulla malesuada fermentum tristique. Quisque magna massa, ornare nec orci vel, convallis ullamcorper neque. Morbi sed ullamcorper velit, sed tristique lectus. Nulla ipsum ipsum, ornare vitae venenatis eu, mollis quis libero.

            Cras ullamcorper tincidunt augue, non sagittis diam sagittis sed. Proin pretium, justo eget fringilla semper, dui orci porttitor velit, sit amet eleifend tortor massa eget diam. Nam condimentum justo et tellus lobortis venenatis. Praesent non magna at purus porta pharetra. Nam eu nibh vitae neque faucibus tincidunt. Proin quis enim ac ex mattis euismod. Pellentesque auctor, nulla eget consectetur lacinia, velit magna porttitor mauris, sit amet aliquam nulla metus dignissim odio. Nulla blandit interdum velit consectetur blandit. Aenean sapien sem, dapibus id nunc et, ornare placerat magna. Nam nec lacinia sapien. Vestibulum eu est sodales, dictum justo eu, commodo eros. Sed et sapien in purus aliquam varius. In cursus elit vel hendrerit vulputate. Nam id ultrices augue, at congue lacus. Suspendisse odio nibh, fringilla euismod pretium ut, sodales sed quam. Cras venenatis tincidunt orci, sit amet sagittis dui ullamcorper sed.

            Sed hendrerit quam vel mauris rhoncus hendrerit. Ut id pharetra sapien. Donec aliquet eros vitae sagittis tempor. Aliquam dictum sit amet urna placerat feugiat. Cras sagittis mi eget est porta, vel imperdiet quam faucibus. In et nunc eu magna tincidunt feugiat sed eu est. Cras finibus nunc dui, vitae pellentesque est bibendum quis. Morbi facilisis posuere libero, eu ultrices nisl tincidunt et. Aenean eu feugiat diam. Nullam auctor ultricies nulla, eu vehicula elit egestas a.

            Nulla facilisi. Mauris sodales elit ligula, at faucibus dolor dapibus eget. Ut id iaculis nunc. Fusce quis urna ex. Phasellus venenatis consequat bibendum. Suspendisse eu orci ut tortor eleifend ullamcorper tincidunt vitae magna. In quis auctor purus. Aenean auctor vestibulum euismod. Nullam vitae ipsum ut massa pellentesque commodo sed vitae ante. Morbi semper laoreet convallis. Ut congue est at diam vehicula blandit. Praesent ornare felis vitae erat dignissim tempor. Phasellus metus metus, condimentum sit amet lacinia a, varius auctor tellus.

            Vivamus congue molestie euismod. Aenean nec ante dui. Fusce id velit urna. Nam gravida tellus eget lectus feugiat, at scelerisque sapien mattis. Quisque vulputate tempus nisl in ultrices. Integer at malesuada magna. Mauris ornare fermentum ex id laoreet. Morbi congue placerat erat non iaculis. Aliquam et laoreet dolor.

            Sed blandit iaculis diam, nec tempor nisi malesuada sed. Nunc est tellus, scelerisque et nisl vel, dapibus tempor felis. Sed venenatis, metus eget condimentum ultrices, magna felis dictum est, non consequat felis purus vel mauris. Vestibulum vitae orci quis nunc mattis maximus ut vel dolor. Praesent dictum condimentum dolor aliquet vulputate. Cras quis blandit ex. Maecenas rutrum elit id nisl blandit, et gravida mauris rhoncus. Curabitur orci orci, consequat ac viverra iaculis, porttitor et ligula.

            Nullam suscipit facilisis sapien, eget placerat leo interdum et. Curabitur eu vulputate est. Phasellus diam ligula, lobortis at pharetra tempus, semper quis velit. Mauris maximus scelerisque elit, vitae varius ante commodo at. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus hendrerit diam massa, non tempor orci scelerisque vitae. Nullam tristique enim mauris, non venenatis nisl condimentum eu. Nulla urna justo, laoreet vel consequat porta, iaculis id dui. Sed in ligula sit amet elit varius pharetra.

            Aenean id scelerisque ligula. Donec fringilla blandit erat, a auctor nunc scelerisque sit amet. Duis sit amet dignissim metus. Morbi blandit ante in dolor gravida, in luctus nisl eleifend. Nulla vitae consequat magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas porttitor felis nisi, in congue massa vestibulum id. Sed sollicitudin metus eget lectus vestibulum, nec auctor metus pretium. Donec sit amet diam a urna auctor euismod. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent ornare eros at arcu imperdiet rutrum. Morbi eleifend vel lectus eu laoreet. 
        </div>
    </Container>
}

export default LegalNotice;